### ISSUE TITLE
Project2 Continue

### ISSUE THREAD

**Issue by jnqian99** [pagand/ORL_optimizer#13]
For half cheetah medium v2,

the R2 values are

R^2 NAR: 0.9920237939804792 R^2 AR: 0.9687655176967382

And for individual states the R2 values are:

state 0 R^2 NAR: 0.7300270795822144 R^2 AR: 0.3690910339355469
state 1 R^2 NAR: 0.7682727426290512 R^2 AR: 0.6152023077011108
state 2 R^2 NAR: 0.9749778918921947 R^2 AR: 0.8899503797292709
state 3 R^2 NAR: 0.9800169412046671 R^2 AR: 0.941743116825819
state 4 R^2 NAR: 0.9236404746770859 R^2 AR: 0.8204318881034851
state 5 R^2 NAR: 0.9874668614938855 R^2 AR: 0.9416524693369865
state 6 R^2 NAR: 0.9486607722938061 R^2 AR: 0.8477649688720703
state 7 R^2 NAR: 0.9722550455480814 R^2 AR: 0.9106765314936638
state 8 R^2 NAR: 0.9922399176284671 R^2 AR: 0.9282858818769455
state 9 R^2 NAR: 0.9421906657516956 R^2 AR: 0.7696249336004257
state 10 R^2 NAR: 0.9783415794372559 R^2 AR: 0.8957170322537422
state 11 R^2 NAR: 0.993208022788167 R^2 AR: 0.9689102619886398
state 12 R^2 NAR: 0.993740382604301 R^2 AR: 0.9761422052979469
state 13 R^2 NAR: 0.967949952930212 R^2 AR: 0.8987857103347778
state 14 R^2 NAR: 0.9961293051019311 R^2 AR: 0.987827131524682
state 15 R^2 NAR: 0.9828768614679575 R^2 AR: 0.9173456653952599
state 16 R^2 NAR: 0.9940944681875408 R^2 AR: 0.9693082924932241

**Comment by jnqian99** [comment]
The graph for state 5 is as follows:



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/4dbc6656-7bad-4304-936c-8b8759050c2c)

**Comment by jnqian99** [comment]
Zoom in view for the above graph near the end of the prediction



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/fd519308-1cba-4277-a83b-b1da121d1647)

**Comment by jnqian99** [comment]
Graph for state 12



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/d49ec936-c7da-4b3e-b671-47a0b72ba203)

**Comment by jnqian99** [comment]
Zoomed in view for above graph



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/34bd076e-d69f-4749-a913-e6bae8b47f1c)

**Comment by jnqian99** [comment]
For state 0:



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/f8a8baa7-c62c-4f1a-99ce-9d0701d9a522)

**Comment by jnqian99** [comment]
Zoomed in view for state 0 near end



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/cbd4e82a-961a-4bf7-afbe-957cdc2aeadc)

**Comment by jnqian99** [comment]
Rewards



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/6db98066-10e9-43c6-935e-dda9447101d0)

**Comment by jnqian99** [comment]
Rewards zoomed in



![Image](https://github.com/pagand/ORL_optimizer/assets/129198370/5e580af8-ed19-4bad-82cb-fca9eff8fdb8)

**Comment by pagand** [comment]
@jnqian99 these are looking good. I have changed it to done.

**Comment by pagand** [comment]
Send back the PR for the commit #[f337764](https://github.com/pagand/ORL_optimizer/pull/14/commits/f33776489fcabe88ca77232df6ba8a238edfb5a3) for review
